services:
  gateway:
    container_name: gateway
    build:
      context: ./backend
      dockerfile: ./cmd/gateway/Dockerfile
    ports:
      - "7010:7010"
    environment:
      - CONFIG_PATH=config/gateway/production.yaml
    depends_on:
      - sso
      - apps
      - clients
      - auth
    networks:
      - app-network
    restart: always

  apps_database:
    container_name: apps_database
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${APPS_DB_NAME}
      POSTGRES_USER: ${APPS_DB_USER}
      POSTGRES_PASSWORD: ${APPS_DB_PASSWORD}
    volumes:
      - apps_init:/docker-entrypoint-initdb.d
      - apps_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APPS_DB_USER} -d ${APPS_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  apps:
    container_name: apps
    build:
      context: ./backend
      dockerfile: ./cmd/apps/Dockerfile
    ports:
      - "7111:7111"
    environment:
      - CONFIG_PATH=config/apps/production.yaml
      - APPS_DB_USER=${APPS_DB_USER}
      - APPS_DB_PASSWORD=${APPS_DB_PASSWORD}
      - APPS_DB_NAME=${APPS_DB_NAME}
    depends_on:
      apps_database:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  client_database:
    container_name: client_database
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${CLIENTS_DB_NAME}
      POSTGRES_USER: ${CLIENTS_DB_USER}
      POSTGRES_PASSWORD: ${CLIENTS_DB_PASSWORD}
    volumes:
      - clients_init:/docker-entrypoint-initdb.d
      - clients_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CLIENTS_DB_USER} -d ${CLIENTS_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  clients:
    container_name: clients
    build:
      context: ./backend
      dockerfile: ./cmd/clients/Dockerfile
    ports:
      - "7113:7113"
    environment:
      - CONFIG_PATH=config/clients/production.yaml
      - CLIENTS_DB_USER=${CLIENTS_DB_USER}
      - CLIENTS_DB_PASSWORD=${CLIENTS_DB_PASSWORD}
      - CLIENTS_DB_NAME=${CLIENTS_DB_NAME}
    depends_on:
      client_database:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  sso_database:
    container_name: sso_database
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${SSO_DB_NAME}
      POSTGRES_USER: ${SSO_DB_USER}
      POSTGRES_PASSWORD: ${SSO_DB_PASSWORD}
    volumes:
      - sso_init:/docker-entrypoint-initdb.d
      - sso_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SSO_DB_USER} -d ${SSO_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  sso:
    container_name: sso
    build:
      context: ./backend
      dockerfile: ./cmd/sso/Dockerfile
    ports:
      - "7115:7115"
    environment:
      - CONFIG_PATH=config/sso/production.yaml
      - SSO_DB_USER=${SSO_DB_USER}
      - SSO_DB_PASSWORD=${SSO_DB_PASSWORD}
      - SSO_DB_NAME=${SSO_DB_NAME}
    depends_on:
      - apps
      - clients
      - sso_database
    networks:
      - app-network
    restart: always

  auth_database:
    container_name: auth_database
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - auth_init:/docker-entrypoint-initdb.d
      - auth_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  auth:
    container_name: auth
    build:
      context: ./backend
      dockerfile: ./cmd/auth/Dockerfile
    ports:
      - "7117:7117"
    environment:
      - CONFIG_PATH=config/auth/production.yaml
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - AUTH_DB_NAME=${AUTH_DB_NAME}
    depends_on:
      - apps
      - clients
      - sso
      - auth_database
    networks:
      - app-network
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - sso_database
      - apps_database
      - client_database

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - prometheus

volumes:
  apps_init:
  apps_data:
  sso_init:
  sso_data:
  clients_init:
  clients_data:
  auth_init:
  auth_data:
  media-data:
  grafana-storage:

networks:
  app-network:
    driver: bridge